language: cpp
compiler:
    - gcc
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq libgtest-dev libmysqlcppconn-dev libboost-dev
    - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
script: cd server && cmake . && make

