### MAKEFILE Arduino

### Emplacements
ARDUINO_DIR	 	= /usr/share/arduino
ARDMK_DIR		= /usr/share/arduino

### Flags Compilateur
CFLAGS_STD		= -std=c11
CXXFLAGS_STD	= -std=c++11
CXXFLAGS		+= -pedantic -Wall -Wextra

### Configuration arduino
BOARD_TAG		 = uno
MONITOR_BAUDRATE  = 9600

include $(ARDMK_DIR)/Arduino.mk